[workspace]
resolver = "2"
members = [
    "2022/day_01/rust",
		"2022/day_02/rust",
		"2022/day_03/rust",
		"2022/day_04/rust",
		"2022/day_05/rust",
		"2022/day_06/rust",
		"2022/day_07/rust",
		"2022/day_08/rust",
		"2022/day_09/rust",
		"2022/day_10/rust"
]
exclude = [ "2022" ]